knp_paginator:
    page_range: 5                      # Default number of pages shown in the pagination menu
    default_options:
        page_name: page                # Parameter name for page number
        sort_field_name: sort          # Parameter name for sort field
        sort_direction_name: direction # Parameter name for sort direction
        distinct: true                 # Ensure distinct results for paginators
        filter_field_name: filterField # Parameter name for filtered field
        filter_value_name: filterValue # Parameter name for filtered value
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # Sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig' # Sort link template
        filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'     # Filtration template 