framework:
    notifier:
        chatter_transports:
            # Si vous utilisez d'autres canaux comme Slack, configurez-les ici
        texter_transports:
            # Pour SMS, si nécessaire
        notification_on_failed_messages: false
        channel_policy:
            # Définir les canaux pour différents niveaux d'importance
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']