framework:
    notifier:
        texter_transports:
            slack: '%env(SLACK_DSN)%'
        channel_policy:
            urgent: ['slack']
            course_alert: ['slack', 'email']
        admin_recipients:
            - { email: 'admin@example.com' }
