security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email  
                password_parameter: password
                enable_csrf: true
                
                
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
            entry_point: App\Security\AppCustomAuthenticator  # ✅ On définit l'entrée
            

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Contrôle d'accès pour certaines routes
    access_control:
    - { path: ^/dashboard_admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard_entraineur, roles: ROLE_ENTRAINEUR }
    - { path: ^/dashboard_responsable_salle, roles: ROLE_RESPONSABLE_SALLE }
    - { path: ^/home, roles: ROLE_SPORTIF }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register/sportif, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }