security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 'admin_password'
                        roles: ['ROLE_ADMIN']
                    responsable:
                        password: 'responsable_password'
                        roles: ['ROLE_RESPONSABLE_SALLE']
                    sportif:
                        password: 'sportif_password'
                        roles: ['ROLE_SPORTIF']
                    entraineur:
                        password: 'entraineur_password'
                        roles: ['ROLE_ENTRAINEUR']
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_ENTRAINEUR: [ROLE_USER]
        ROLE_RESPONSABLE_SALLE: [ROLE_USER]
        ROLE_SPORTIF: [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\AppCustomAuthenticator
                - App\Security\GoogleAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 week
                path: /
            entry_point: App\Security\AppCustomAuthenticator

    access_control:
    - { path: ^/api/auth/google, roles: PUBLIC_ACCESS }
    - { path: ^/connect, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register/sportif, roles: PUBLIC_ACCESS }
    - { path: ^/app_forget_password, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }
    - { path: ^/admin/user, roles: ROLE_ADMIN }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard_entraineur, roles: ROLE_ENTRAINEUR }
    - { path: ^/dashboard_responsable_salle, roles: ROLE_RESPONSABLE_SALLE }
    - { path: ^/home, roles: ROLE_SPORTIF }
    - { path: ^/reclamation, roles: ROLE_USER }
    - { path: ^/responsable/user, roles: ROLE_RESPONSABLE_SALLE }
    - { path: ^/responsable, roles: ROLE_RESPONSABLE_SALLE }
    - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
                