white_october_breadcrumbs:
    separator:          '/'
    separatorClass:     'separator'
    listId:             'wo-breadcrumbs'
    listClass:          'breadcrumb'
    itemClass:          ''
    linkRel:            ''
    locale:             ~
    translation_domain: ~
    viewTemplate:       '@WhiteOctoberBreadcrumbs/microdata.html.twig' 