# config/services.yaml
parameters:
    activities_image_directory: '%kernel.project_dir%/public/uploads/activities'
    uploads_directory: '%kernel.project_dir%/public/uploads/images/users'
    upload_directory: '%kernel.project_dir%/public/uploads/images/users'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    users_images_directory: '%kernel.project_dir%/public/uploads/images/users'
    events_images_directory: '%kernel.project_dir%/public/uploads/events'
    teams_images_directory: '%kernel.project_dir%/public/uploads/teams'
    uploads_public_path: '/uploads'
    deepinfra_api_key: '%env(DEEPINFRA_API_KEY)%'
    stripe_secret_key: 'sk_test_51R6XfmCvMipSUHQuaVylRxEIETrWqy4OtYXPBegkEIcFhkUUkByDt8EixxdDNh1ekcHSdVAUGNRr7BUsfXFEc5VX00CqsNejm0'
    stripe_public_key: 'pk_test_51R6XfmCvMipSUHQuBPuvGSEoyT4USxinzYkBENoYz4C2LSYzsB46fd6CgJaXzAtDOUP7prhW651vB3CP6CM9PgvL009edX6abt'
    twilio.account_sid: '%env(string:TWILIO_ACCOUNT_SID)%'
    twilio.auth_token: '%env(string:TWILIO_AUTH_TOKEN)%'
    twilio.phone_number: '%env(string:TWILIO_PHONE_NUMBER)%'
    RECAPTCHA_SITE_KEY: '%env(RECAPTCHA_SITE_KEY)%'
    google_client_id: '426973845068-m2kpmpksncdup4069cl4c7a7rrchls9l.apps.googleusercontent.com'
    google_client_secret: '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'
    google_redirect_uri: 'http://localhost:8000/callback'
    teams_images_base_url: '/uploads/teams/'
    app.token_secret: '%env(TOKEN_SECRET)%'
    router.request_context.host: '6933-197-15-91-100.ngrok-free.app'
    router.request_context.scheme: 'https'

services:


    # default configuration for services in *this* file

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $twilioAccountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $twilioAuthToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'

    App\Controller\AdminReclamationController:
        arguments:
            $logger: '@monolog.logger'

    App\Service\TranslationService:
        arguments:
            $logger: '@monolog.logger'

    App\Service\EmailUniquenessValidator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Security\ClientRegistry: ~

    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'

    

    App\Service\TwilioService:
        arguments:
            $params: '@parameter_bag'

    App\Service\WeatherService:
        arguments:
            
            #$stripeSecretKey: '%stripe_secret_key%'
            $httpClient: '@http_client'
            $apiKey: '%env(WEATHER_API_KEY)%'        
    

    # Add any other service definitions below


    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    

  

    # Add any other service definitions below

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    
        

    # Add any other service definitions below
