# config/services.yaml
parameters:
    activities_image_directory: '%kernel.project_dir%/public/uploads/activities'
    uploads_directory: '%kernel.project_dir%/public/uploads/images/users'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    users_images_directory: '%kernel.project_dir%/public/uploads/images/users'
    events_images_directory: '%kernel.project_dir%/public/uploads/events'
    teams_images_directory: '%kernel.project_dir%/public/uploads/teams'
    uploads_public_path: '/uploads'
    RECAPTCHA_SITE_KEY: '%env(RECAPTCHA_SITE_KEY)%'
    stripe_secret_key: 'sk_test_51R6XfmCvMipSUHQuaVylRxEIETrWqy4OtYXPBegkEIcFhkUUkByDt8EixxdDNh1ekcHSdVAUGNRr7BUsfXFEc5VX00CqsNejm0'
    stripe_public_key: 'pk_test_51R6XfmCvMipSUHQuBPuvGSEoyT4USxinzYkBENoYz4C2LSYzsB46fd6CgJaXzAtDOUP7prhW651vB3CP6CM9PgvL009edX6abt'
    deepinfra_api_key: '%env(DEEPINFRA_API_KEY)%'
   
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\AdminReclamationController:
        arguments:
            $logger: '@monolog.logger'

    App\Service\TranslationService:
        arguments:
            $logger: '@monolog.logger'

    App\Service\EmailUniquenessValidator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Security\ClientRegistry: ~

    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
