# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    activities_image_directory: '%kernel.project_dir%/public/uploads/activities'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    # chemin public utilisable dans asset() pour afficher l'image
    uploads_public_path: '/uploads'

    images_directory: '%kernel.project_dir%/public/uploads/images'
    users_images_directory: '%kernel.project_dir%/public/uploads/images'
    events_images_directory: '%kernel.project_dir%/public/uploads/events'
    
    # IBM Watson Speech to Text configuration
    ibm_watson_api_key: 'JR-LCWjnds3scsjrtCtn2wCNlyR2GWGAQq_hJ1D6Fhh-'
    ibm_watson_service_url: 'https://api.au-syd.speech-to-text.watson.cloud.ibm.com/instances/760398a7-3622-4319-83f8-415080a4ee25'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Service\EmailUniquenessValidator:
        arguments:
           ^ $entityManager: '@doctrine.orm.entity_manager'
    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            
    App\Service\SpeechToTextService:
        arguments:
            $apiKey: '%ibm_watson_api_key%'
            $serviceUrl: '%ibm_watson_service_url%'
            
    App\Service\PerspectiveApiService:
        public: true
        
    App\Service\EmailJSService:
        public: true
            
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
